### ISSUE TITLE
SETH_CNN.pt not available

### ISSUE THREAD

**Issue by HiracharleFranklin** [DagmarIlz/SETH#1]
Hi, thank you for your great work! But it seems that the model at https://rostlab.org/~deepppi/SETH_CNN.pt is not avaliable now. Can you check it and provide a new one? Thanks again.

**Comment by DagmarIlz** [comment]
Hi,
I have added the model in the CNN folder here in GitHub.

**Comment by HiracharleFranklin** [comment]
Thank you!
